config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registration: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :managers, controllers: {
    sessions: 'managers/sessions',
    passwords: 'managers/passwords',
    registration: 'managers/registrations'
  }
  devise_scope :manager do
    get '/managers/sign_out', to: 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registration: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  

  namespace :admin do
    resources :companies, except: [:show] do
      resources :managers, except: [:show]
    end
  end

  resources :companies, only: [] do
    resources :status, only: [:index]
    resources :uses, except: [:show]
    resources :cars, only: [] do
      resources :uses, except: [:show]
      get '/ride', to: 'status#ride'
      get '/no_ride', to: 'status#no_ride'
      resources :reservations, only: [:index, :new, :create, :destroy]
    end

    namespace :manager do
      resources :managers, except: [:show]
      resources :users, except: [:show] do
        resources :cards, only: [:edit, :update]
      end
      get '/monthly_report', to: 'cars#monthly_report'
      get '/half_period_report', to: 'cars#half_period_report'
      resources :cars do
        resources :uses, except: [:show]
        resources :inspections, except: [:show]
        resources :memos, except: [:show]
      end
    end
  end
end

app/controllers/manager/uses_controller.rb
class Manager::UsesController < ApplicationController
  layout 'manager'
  before_action :authenticate_manager!
  before_action :check_manager_company
  before_action :set_use, only: %i(edit update destroy)
  before_action :set_company_and_car

  def index
    @uses = @car.uses.order(created_at: :desc)
  end

  def new
    @use = @car.uses.build
  end

  def edit
  end

  def create
    @use = @car.uses.build(use_params)
    if @use.inspection_st == '車検依頼'
      @car.update(state: '車検中')
    else
      @car.update(state: '空車')
    end
    if @use.save
      if @use.id > @car.uses.order(:id).first.id
        @use.update(distance: @use.odometer - @car.uses.where("id < #{@use.id}").order(:id).last.odometer)
      else
        @use.update(distance: @use.odometer - @car.initial_odometer)
      end
      if @car.uses.where.not(refueling_amount: 0).count >=2
        @car.update(mileage: (@car.uses.where.not(refueling_amount: 0).order(:id).last.odometer - @car.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/@car.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)
      end
      redirect_to company_manager_car_uses_path(@company, @car), notice: '新規登録完了'
    else
      render :new
    end
  end

  def update
    if @use.update(use_params)
      if @use.inspection_st == '車検依頼'
        @car.update(state: '車検中')
      else
        @car.update(state: '空車')
      end
      if @use.id > @car.uses.order(:id).first.id
        @use.update(distance: @use.odometer - @car.uses.where("id < #{@use.id}").last.odometer)
      else
        @use.update(distance: @use.odometer - @car.initial_odometer)
      end
      if @car.uses.where.not(refueling_amount: 0).count >= 2
        @car.update(mileage: (@car.uses.where.not(refueling_amount: 0).order(:id).last.odometer - @car.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/@car.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)
      end
      redirect_to company_manager_car_uses_path(@company, @car), notice: '変更完了'
    else
      render :edit
    end
  end

  private
    def set_use
      @use = Use.find(params[:id])
    end

    def set_company_and_car
      @company = Company.find(params[:company_id])
      @car = Car.find(params[:car_id])
    end

    def use_params
      params.require(:use).permit(:use_day, :odometer, :destination, :refueling_amount, :wash, :oil_change, :self_inspection, :inspection_st, :user_id, :car_id)
    end
end

app/controllers/uses_controller.rb
class UsesController < ApplicationController
  layout 'user'
  before_action :authenticate_user!
  before_action :check_user_company
  before_action :set_company_and_car
  before_action :set_use, only: %i(edit update destroy)

  def index
    @uses = @car.uses.order(created_at: :desc)
  end

  def new
    @use = @car.uses.build
    render layout: 'user_only_yield'
  end

  def edit
  end

  def create
    @use = @car.uses.build(use_params)
    if @use.inspection_st == '車検依頼'
      @car.update(state: '車検中')
    else
      @car.update(state: '空車')
    end
    if @use.save
      if @use.id > @car.uses.order(:id).first.id
        @use.update(distance: @use.odometer - @car.uses.where("id < #{@use.id}").order(:id).last.odometer)
      else
        @use.update(distance: @use.odometer - @car.initial_odometer)
      end
      if @car.uses.where.not(refueling_amount: 0).count >= 2
        @car.update(mileage: (@car.uses.where.not(refueling_amount: 0).order(:id).last.odometer - @car.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/@car.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)
      end
      redirect_to company_car_uses_path(@company, @car), notice: '新規登録完了'
    else
      render :new
    end
  end

  def update
    if @use.update(use_params)
      if @use.inspection_st == '車検依頼'
        @car.update(state: '車検中')
      else
        @car.update(state: '空車')
      end
      if @use.id > @car.uses.order(:id).first.id
        @use.update(distance: @use.odometer - @car.uses.where("id < #{@use.id}").order(:id).last.odometer)
      else
        @use.update(distance: @use.odometer - @car.initial_odometer)
      end
      if @car.uses.where.not(refueling_amount: 0).count >= 2
        @car.update(mileage: (@car.uses.where.not(refueling_amount: 0).order(:id).last.odometer - @car.uses.where.not(refueling_amount: 0).order(:id).last(2).first.odometer)/@car.uses.where.not(refueling_amount: 0).order(:id).last.refueling_amount)
      end
      redirect_to company_car_uses_path(@company, @car), notice: '変更完了'
    else
      render :edit
    end
  end

  private
    def set_use
      @use = Use.find(params[:id])
    end

    def set_company_and_car
      @company = Company.find(params[:company_id])
      @car = Car.find(params[:car_id])
    end

    def use_params
      params.require(:use).permit(:use_day, :odometer, :destination, :refueling_amount, :wash, :oil_change, :self_inspection, :inspection_st, :user_id, :car_id)
    end
end

app/views/uses/_form.html.slim
= form_with(model: [@company, @car, use], local: true) do |form|
  - if use.errors.any?
    #error_explanation
      ul
        - use.errors.full_messages.each do |message|
          li
            = message
  .field.row
    .col-4.text-right
      = form.label :利用日
    .col-8
      = form.date_select :use_day
  .field.row.font-weight-bold.align-items-center
    .col-4.text-right
      = form.label :メーター
    .col-8
      = form.number_field :odometer
      br
      - if @use.id
        - if @use.id == @car.uses.order(:id).first.id
          | (ひとつ前 #{@car.initial_odometer})
        - else
          | (ひとつ前 #{@car.uses.where('id < ?', @use.id).order(:id).last.odometer})
      - else
        - if @car.uses.count > 0
          | (前回 #{@car.uses.order(:id).last.odometer})
        - else
          | (前回 #{@car.initial_odometer})
  .field.row.font-weight-bold
    .col-4.text-right
      = form.label :行先
    .col-8
      = form.text_field :destination, size:"15"
  .field.row
    .col-4.text-right
      = form.label :給油量
    .col-8
      - if @use.id
        = form.number_field(:refueling_amount, step: '0.01')
      - else
        = form.number_field(:refueling_amount, step: '0.01', value:'0.00')
  .field.row
    .col-4.text-right
      = form.label :洗車
    .col-8
      = form.select :wash, ['無','有']
  .field.row
    .col-4.text-right
      = form.label :オイル交換
    .col-8
      = form.select :oil_change, ['無','有']
  .field.row
    .col-4.text-right
      = form.label :自主点検
    .col-8
      = form.select :self_inspection, ['無','有']
  .field.row
    .col-4.text-right
      = form.label :車検
    .col-8
      = form.select :inspection_st, ['無','車検依頼']
  = form.hidden_field :user_id, value: current_user.id
  .actions.text-right
    -if @use.id
      = link_to '戻る', company_car_uses_path(@company, @car), class:'btn btn-outline-success text-success'
    - else
      = link_to '戻る', company_status_index_path(@company), class:'btn btn-outline-success text-success'
    |　
    = form.submit('登録', class: 'btn btn-success')

app/views/uses/edit.html.slim
h2.pt-2.pd-2
  | 利用実績編集
br
= render 'form', use: @use
= link_to '戻る', company_car_uses_path(@company, @car)

app/views/uses/index.html.slim
h2.pt-2.pd-2
  | 利用実績
h5.font-weight-bold
  = @car.car_name
  |  
  = @car.number
  |　
  = link_to '戻る', company_status_index_path(@company), class:'btn btn-sm btn-outline-success text-success'
.table-responsive
  table.table.table-bordered.text-nowrap
    thead.text-center
      tr
        td
          | 利用日
        td
          | 利用者
        td
          | 行先
        td
          | メーター
        td
          | 走行距離
        td
          | 給油
        td
          | 洗車
        td
          | ｵｲﾙ交換
        td
          | 自主点検
        td
          | 編集
    tbody
      - @uses.each do |use|
        - last_use = @car.uses.where("id < #{use.id}").order(:id).last
        tr
          td
            = l use.use_day, format: :default
          td.text-center
            = User.find(use.user_id).user_name
          td
            = use.destination
          td.text-right
            = use.odometer.to_s(:delimited)
          td.text-right
            = use.distance.to_s(:delimited)
            | km
          td.text-right
            = sprintf("%.2f", use.refueling_amount)
            | ℓ
          td.text-center
            = use.wash
          td.text-center
            = use.oil_change
          td.text-center
            = use.self_inspection
          td.text-center
            - if use.user == current_user
              = link_to '編集', edit_company_car_use_path(@company, @car, use), class:'btn-secondary btn-sm'

app/views/uses/new.html.slim
h2.pt-2.pd-2
  | 実績新規登録
br
= render 'form', use: @use