config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registration: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :managers, controllers: {
    sessions: 'managers/sessions',
    passwords: 'managers/passwords',
    registration: 'managers/registrations'
  }
  devise_scope :manager do
    get '/managers/sign_out', to: 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registration: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  

  namespace :admin do
    resources :companies, except: [:show] do
      resources :managers, except: [:show]
    end
  end

  resources :companies, only: [] do
    resources :status, only: [:index]
    resources :uses, except: [:show]
    resources :cars, only: [] do
      resources :uses, except: [:show]
      get '/ride', to: 'status#ride'
      get '/no_ride', to: 'status#no_ride'
      resources :reservations, only: [:index, :new, :create, :destroy]
    end

    namespace :manager do
      resources :managers, except: [:show]
      resources :users, except: [:show] do
        resources :cards, only: [:edit, :update]
      end
      get '/monthly_report', to: 'cars#monthly_report'
      get '/half_period_report', to: 'cars#half_period_report'
      resources :cars do
        resources :uses, except: [:show]
        resources :inspections, except: [:show]
        resources :memos, except: [:show]
      end
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :managers, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :cars, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  before_action :set_company, only: %i(edit update destroy)

  def index
    @company = Company.all
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to admin_companies_path, notice: '新規登録完了'
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to admin_companies_path, notice: '更新完了'
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to admin_companies_path, notice: '削除完了'
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/views/admin/companies/_form.html.slim
= form_with(model: [:admin, company], local: true) do |form|
  - if company.errors.any?
    #error_explanation
      ul
        - company.errors.full_messages.each do |message|
          li
            = message
  .field
    .row
      .col-5
        = form.label :会社名
      .col-7
        = form.text_field :name
  .actions
    = form.submit("登録", class:'btn btn-primary')

app/views/admin/companies/edit.html.slim
.row.pt-4.pb-2.align-items-center
  .col.h3
    = @company.name
    |  会社情報編集
= render 'form', company: @company

app/views/admin/companies/index.html.slim
.row.pt-4.pb-2.align-items-center
  .col.h3
    | 会社一覧
.table-responsive
  table.table.table-sm.table-bordered.table-striped.text-nowrap
    thead.text-center
      tr
        th
          | 会社id
        th
          | 会社名
        th
          | 会社情報
    tbody
      - @company.each do |company|
        tr
          td.align-middle.text-center
            = company.id
          td.align-middle.text-center
            = company.name
          td.text-center
            = link_to '編集', edit_admin_company_path(company), class:'btn btn-outline-secondary text-secondary btn-sm'
            |　　
            = link_to '削除', admin_company_path(company), class:'btn btn-outline-secondary text-secondary btn-sm', method: :delete, data: { confirm: '本当に削除しますか?' }
            |　　
            = link_to '管理ユーザー一覧', admin_company_managers_path(company), class:'btn btn-outline-secondary text-secondary btn-sm'
br
= link_to '新規登録', new_admin_company_path, class:'btn btn-outline-primary text-primary'

app/views/admin/companies/new.html.slim
.row.pt-4.pb-2.align-items-center
  .col.h3
    | 会社新規登録
= render 'form', company: @company